FROM ubuntu:22.04

RUN sed -i -E 's/(archive|security).ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN apt-get update \
    && apt-get install -y git build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev

RUN useradd -s /bin/bash -m vscode \
 && groupadd docker \
 && usermod -aG docker vscode

USER vscode

